### PR TITLE
[ci] fix ci not fail when some testcase failed

### LINKED ISSUE #3652: [Bug Report] [test] some testcase failed, but ci `build and test` action passed
# Bug Report

**Starcoin version:**

[369a4d3](https://github.com/starcoinorg/starcoin/commit/369a4d37d02044b6b5fd9f5ad7a0986403a14397)

**Current behavior:**

run `cargo test --package starcoin-transactional-test-harness --test tests` fails 
But ci on *pr* and *push* passed

**Expected behavior:**

ci should fail and block the merging of pr

**Steps to reproduce:**

run `cargo test --package starcoin-transactional-test-harness --test tests` fails with 
```
failures:
    run_test::cases/arg_variable.move

test result: FAILED. 7 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p starcoin-transactional-test-harness --test tests
```
image

**Related code:**

```
insert short code snippets here
```

**Other information:**

found testcase failures:

cargo test --package starcoin-transactional-test-harness --test tests
cargo test --package starcoin-vm-types --lib -- account_address::test::address_hash --exact --nocapture
cargo test --package starcoin-vm-types --lib -- unit_tests::access_path_test::test_access_path_str_valid --exact

### PR DESCRIPTION
**Pull request by jiangying000**
## Pull request type

add multiple space match to grep some failure output 

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [*] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: fix #3652

## What is the new behavior?

-
-
-

### CODE REVIEW

File: scripts/auto_rerun_test.sh [hunk 1]
```diff
@@ -15,7 +15,7 @@ ulimit -a
 
 #pleanse ensure tow test command's argument is same.
 RUST_LOG=OFF RUST_BACKTRACE=0 cargo xtest --exclude starcoin-move-prover -j 15 -- --test-threads=10 --color never --format pretty |tee "$TEST_RESULT_FILE" ||true
-grep -e '^test[[:space:]][^[:space:]]*[[:space:]]\.\.\.[[:space:]]FAILED' "$TEST_RESULT_FILE" >"$TEST_RESULT_FAILED_FILE" ||true
+grep -e '^test[[:space:]][^[:space:]]*[[:space:]]\+\.\.\.[[:space:]]FAILED' "$TEST_RESULT_FILE" >"$TEST_RESULT_FAILED_FILE" ||true
```
Comment (jiangying000) [inline scripts/auto_rerun_test.sh:18]: use `[[:space:]]\+` to match multiple space output of `cargo test --package starcoin-transactional-test-harness --test tests` like

    test run_test::cases/arg_variable.move         ... FAILED

**Review by jolestar — APPROVED** [review]

**Review by 0xpause — COMMENTED** [review]
access_path_test.rs 中有两个 case 测试失败，这里漏了一个。
详情参考: https://github.com/starcoinorg/starcoin/issues/3654
