### PR TITLE
fix #3309

### LINKED ISSUE #3309: bug: life time error when update actix and tokio
# Bug Report

**Starcoin version:**
#3271 

**Current behavior:**
```
> dev get-coin
txn 0x27973db496b7088f6ba6b5a173d036ec0cda8cb6a966c30e528193d9fdb66967 submitted.
Mailbox has closed
```

**Expected behavior:**
should not panic

**Steps to reproduce:**
```shell
> starcoin -n dev console
> dev get-coin
```

**Related code:**

```
insert short code snippets here
```

**Other information:**

### PR DESCRIPTION
**Pull request by LemonHX**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
bug

Issue Number: #3309

## What is the new behavior?
as before

### CODE REVIEW

File: rpc/client/src/lib.rs [hunk 1]
```diff
@@ -134,19 +135,25 @@ impl RpcClient {
...
         let inner: RpcClientInner = provider.get_rpc_channel().map_err(map_err)?.into(); //Self::create_client_inner(conn_source.clone()).map_err(map_err)?;
         let pubsub_client = inner.pubsub_client.clone();
+        let (handle_exit_sender, handle_exit_receiver) = oneshot::channel::<()>();
         let handle = std::thread::spawn(move || {
-            let sys = System::with_tokio_rt(|| {
+            let _sys = System::with_tokio_rt(|| {
                 tokio::runtime::Builder::new_multi_thread()
                     .enable_all()
-                    .on_thread_stop(|| debug!("client-actix-system thread stopped"))
+                    .on_thread_stop(|| println!("client-actix-system thread stopped"))
```
Comment (jolestar) [inline rpc/client/src/lib.rs:143]: 建议不要直接 println, 会影响命令行的输出结果。日志是输出在 stderr 中的。

**Review by jolestar — APPROVED** [review]
可以把集成测试打开试试 #3303

**Comment by jolestar** [comment]
或者这个直接 merge 进去，然后 #3303 那边 rebase 一下。
